### ISSUE TITLE
unable to register plugin to new device

### ISSUE THREAD

**Issue by cramos18** [oodesign/merge-duplicate-symbols#100]
Hi, 

Is there a way to deregister the plugin on my old laptop, I am unable to register merge duplicates on my new laptop as it says all my seats are full. Nothing happens when I click on settings in plugins.

**Comment by oodesign** [comment]
Hi @cramos18 ,

We've sent you an e-mail regarding your issue, so that we can continue the conversation there.

Thanks for reaching out!
