### ISSUE TITLE
Cannot register plugin to new device

### ISSUE THREAD

**Issue by sbfu** [oodesign/merge-duplicate-symbols#101]
Hi,
I removed this plugin from an old work laptop but cannot register it on the new laptop. Merge Duplicates tells me all seats are full. 
Perhaps I didn't deregister properly? Are you able to help me fix this?

**Comment by oodesign** [comment]
Hi @sbfu ,

We're trying to keep GitHub issues for technical issues related with Merge Duplicates.
For licensing questions, may you please [send us an email to oscar@oodesign.me](oscar@oodesign.me)?

Thanks for reaching out!
