### ISSUE TITLE
Version of Sketch Required

### ISSUE THREAD

**Issue by btarsenko** [oodesign/merge-duplicate-symbols#108]
Hi, I was wondering if this plugin requires a certain version of Sketch? Our company has a limited Sketch license, so we are only available to remain at Sketch 67.2 (I believe Sketch is on 69).

When I try to install plugin using License Key, it is spinning forever and ever and will not respond. I am wondering if this has something to do with the version of software?

Thank you,

Brittany

**Comment by oodesign** [comment]
I'm closing the issue as we're following up via mail.
