### ISSUE TITLE
[Improvement?] When merging duplicate symbols, apply changes to symbol overrides

### ISSUE THREAD

**Issue by johnkeese** [oodesign/merge-duplicate-symbols#11]
Love the plugin, thanks so much for your work on it!

**Suggested Improvement**
As a user, when merging duplicate symbols I expect symbol overrides to be updated as well.

For example, I have multiple symbols that are all the same but some instances are used as symbol overrides. When merging symbols some overrides stay linked while others are now missing (and replaced by the red /// placeholder graphic)

**Comment by oodesign** [comment]
Hi John,

Sorry for the late reply! We've been catching some other waves and left the plugin aside for a while.
The next logical step for the plugin is to update also all the symbol overrides. It's a pretty obvious one :)

We've made a first try and getting some performance issues, but I'll make sure to let you know when we release a stable version that solves this issue.

Thanks for the feedback!

**Comment by danielguillan** [comment]
@oodesign any progress on this? Is there a work in progress version we could play with?

Thanks for this great plugin!

**Comment by oodesign** [comment]
Hello @johnkeese and @danielguillan!

We just released v3.0.0, and symbol overrides are now updated too when you merge duplicate symbols.
Please, give it a try and let us know how did it work for you or if you had any issues!

Thanks :)

**Comment by johnkeese** [comment]
@oodesign thanks for the update! Really appreciate the extra info about overrides.

One question though (and perhaps it's my fault) but when merging symbols any text or attributes that are overridden are being reset. For example...

**Symbols view**
![symbols](https://user-images.githubusercontent.com/3217063/33839571-3a36f1e6-de58-11e7-9fc9-c092d201e451.png)

**Artboard before merge**
Text has been change from "Default" to various things in the Overrides panel.
![before merge](https://user-images.githubusercontent.com/3217063/33839647-707d7a22-de58-11e7-80e5-0f8058abcd93.png)

**Artboard after merge**
Text on merged symbol has been reset to "Default". Expected override text to still be present.
![after merge](https://user-images.githubusercontent.com/3217063/33839651-73e2f0fc-de58-11e7-96d9-4c9991a1bbef.png)

Thoughts? Does this need to be another improvement? Or is it a bug?

Regardless, thanks for an awesome plugin
