### ISSUE TITLE
Merge duplicate symbols not updating

### ISSUE THREAD

**Issue by hiyaneko** [oodesign/merge-duplicate-symbols#110]
Hello!! I purchased this app a while ago and it's now stuck on ver. 5.0.1 and doesn't want to update anymore :( what can I do with that?

**Comment by oodesign** [comment]
Hi @hiyaneko ,

Sinve v6 Merge Duplicates is back to the public domain. You can get the latest release directly [from GitHub](https://github.com/oodesign/merge-duplicate-symbols/releases), and all updates will appear in Sketch as they are released, as any other plugin.

The first time you trigger Merge Duplicates it may ask you for your license key (that you may find in your Gumroad receipt). 
If you are not able to find it please [send us an email](mailto:oscar@oodesign.me) with the email account you used to purchase your license, and I'll be happy to have it resent to you.

Thanks for reaching out!
