### ISSUE TITLE
Merge selected

### ISSUE THREAD

**Issue by bmolena** [oodesign/merge-duplicate-symbols#114]
Is there a way to merge selected layer or text styles? Also is there a way to only view the duplicates in the file you're in?

**Comment by oodesign** [comment]
Hi @bmolena,

Absolutely! You can merge selected layer/text styles by using the "Merge layer/text styles (from list)" options.
Merge duplicates will list all of your layer/text styles, allow you to select the ones you'd like to merge, choose which you want to keep, and merge them (removing the discarded styles, and applying the chosen one where the discarded styles were applied).

All the Merge Duplicates options do have an option (in the bottom left corner) to enable/disable considering also linked libraries. 

You can also enable/disable looking into linked libraries as a general option in the plugin settings page. You may find the option in Plugins > Merge Duplicate... > Settings.

Hope it helps!
