### ISSUE TITLE
How to recover a license

### ISSUE THREAD

**Issue by FilueDiSantu** [oodesign/merge-duplicate-symbols#116]
Hi guys. I've reinstalled an OS on my macbook back from a beta Big Sur to a stable Catalina and can't enter my S/N to active the plugin now.

Email - filue.di.santu@gmail.com

**Comment by oodesign** [comment]
Hi @FilueDiSantu,

We're trying to keep GitHub just for technical issues related with the plugin. 
May you please [send us an email](mailto:oscar@oodesign.me) with your purchase details (email used for the purchase, and license key) so that we can continue this conversation there?

Thanks a lot! 🥰
