### ISSUE TITLE
Reinstalled Sketch on the same device - Plugin license key limit

### ISSUE THREAD

**Issue by franciscamaalves** [oodesign/merge-duplicate-symbols#119]
Just bought Merge Duplicates Single license.  I've reinstalled my Sketch app and for my surprise the plugin was not working anymore. I get the "All seats are busy" error message.

How can I recover and benefit from it again

**Comment by oodesign** [comment]
Hi @franciscamaalves ,

I'm closing the issue as I believe we're already addressing the issue via email.
Otherwise, please feel free to reopen it. 😊

Thank you!
