### ISSUE TITLE
Doesn't work with library symbols

### ISSUE THREAD

**Issue by RaphyRaph** [oodesign/merge-duplicate-symbols#12]
You can only merge local symbols with library symbols when they have an instance already in the file. Ideally, merging allows includes library symbols regardless of whether they're already in the file. 

A hacky way to do this would be to insert all the instances of synced symbols in a temporary page, run the merger, and then delete them.

When you go through merging process, it should show you which is a library symbols vs a local one.

**Comment by oodesign** [comment]
Hi Raphaël!

Sorry for the late reply! We've been catching some other waves and left the plugin aside for a while.
We still haven't tested anything with libraries, but we sure will. 

Just to make sure we got you right... What you're trying to do is:

1. You have a Sketch file that uses some local symbols and some symbols that come from other Sketch (new feature) libraries.
2. Some of those symbols (local and library ones) have the same name
3. The plugin is not finding the ones in the libraries, and therefore can't be merged

Is that right?

Thanks for the feedback!

**Comment by RaphyRaph** [comment]
yes, this is correct. In the process of switching over to libraries or retrofitting old files, this would help getting set up quickly.

**Comment by cimaja** [comment]
Hi guys, I was able to repro this too. I've a simple file with duplicate symbols. If I use the plugin everything works like a charm but  If that file is set as a library in sketch, then using the plugin doesn't merge the duplicate symbols. Let me know if you need more details.
