### ISSUE TITLE
Licens Key 

### ISSUE THREAD

**Issue by Evans74** [oodesign/merge-duplicate-symbols#125]
Hello,
I can't find the license key in my email. How can I do?

THX

**Comment by oodesign** [comment]
Hi @Evans74 ,

May you please [send us an email](mailto:oscar@oodesign.me) with the email you used to purchase your license in Gumroad?

Thanks!

**Comment by Evans74** [comment]
Ok i send you a mail from ale.eva@libero.it

**Comment by oodesign** [comment]
Got it, thanks!

I'm closing this issue as we're continuing the conversation via mail 😊

**Comment by Evans74** [comment]
unfortunately after I enter the license it gives me this error!
"All seats are busy! Looks like this liense has already benn installed on as many devices...."

The macbook I use was replaced and I re-installed sketch.
