### ISSUE TITLE
Unreponsive

### ISSUE THREAD

**Issue by naruelle** [oodesign/merge-duplicate-symbols#126]
I have couple of symbols from a library that it's linked to. Previously it would merge everything. I don't know what changed, but now even though I push the button, it just won't do anything. It's not frozen. Not sure if it's doing anything but to the users, it seems like nothing is happening. I keep waiting but nothing happens.

**Comment by oodesign** [comment]
Hi!

I'm closing this issue as it's being addressed in [Issue #127 ](https://github.com/oodesign/merge-duplicate-symbols/issues/127)
