### ISSUE TITLE
Merging library symbols

### ISSUE THREAD

**Issue by RaphyRaph** [oodesign/merge-duplicate-symbols#13]
Merging library symbols:
- previews are not available 
- you can't tell which library the symbol is coming from, or whether it's a local symbol

![bitmap](https://user-images.githubusercontent.com/3810802/31490129-d97af286-af3a-11e7-96fe-8c143c4dd149.png)

**Comment by oodesign** [comment]
Hi Raphaël!

We still haven't tested anything with libraries, but we sure will. 
The plugin is currently just looking for name-duplicate symbols locally in the Sketch file (local symbols).

Can you give us some more detail about how did you get to the scenario you described?
Or... may you attach the Sketch file (or send it to oodesignux@gmail.com) for us to check it directly?

Thanks for the feedback!

**Comment by RaphyRaph** [comment]
to recreate the above situation, insert 1 symbols with the same name from 2 different libraries and try to merge.

**Comment by cimaja** [comment]
I confirm that issue, where we can't have a preview of a symbol coming from the Library

**Comment by patrickplaggenborg** [comment]
I have the same problem, not seeing a preview of symbols. Looks like they indeed come from a Library. They can be multiple 'instances' in the current document, referring to the same Library Symbol.

**Comment by hyunsk** [comment]
Hi Raph! Thanks so much for making this plugin! I use it quite often. 
Is it possible to get a label showing which library the symbol belongs to? I also use a library and the main use case I have is merging instances back to my symbol library. 
Currently I've made the mistake of merging instances to the local symbol library which I don't want.

**Comment by RaphyRaph** [comment]
@hyunsk use this instead https://github.com/sonburn/symbol-swapper

**Comment by oodesign** [comment]
Hi all!

Is that still happening? We've been trying it out, and seems to work fine...

![im02](https://user-images.githubusercontent.com/11992834/37067443-14c6723e-21aa-11e8-86d1-34e44c22d120.JPG)

In the file:
 - The red oval comes from Library1
 - The purple and green ovals come from Library2
 - And the blue oval is a local symbol (you may see it in the screenshot).

And when we launch the plugin, everything seems to work properly. 
Merge happens in the local file, obviously. We can't (and won't) affect the Shared Libraries files.

![im03](https://user-images.githubusercontent.com/11992834/37067503-72914ce0-21aa-11e8-8987-851d0b07a84c.JPG)

Is there something we're missing?

**Comment by hyunsk** [comment]
@oodesign 
Hey Oscar!

Yeah as far as I can tell it's still an issue. The previews show but the text description of the symbol should be more descriptive. In nearly all of the situations when I use merge duplicate symbols I am merging visually identical symbols so a distinction between library and current sketch file symbols would be hugely helpful. 

There is still a bug in Sketch that creates duplicate symbols to be created when copying instances. When using the merge duplicate symbols I am often looking at something like this.

![merge symbols library](https://user-images.githubusercontent.com/966955/37179395-50d8494c-22da-11e8-8a4f-4a2631992a05.png)

It would be very helpful to if there were symbol names and sources in the plugin. 

Thanks!

**Comment by oodesign** [comment]
I see! Let me see what we can do about that :)

**Comment by trgm** [comment]
Yeah where the symbols came from would help a lot. That or breadcrumbs.

**Comment by oodesign** [comment]
We just released v3.0.2, which should show the Library name where the symbol comes from (which is cool!)

But no so cool is that we still have an issue when mergin symbols. When the discarded symbols come from a library, for some reason, are not really discarded, and the plugin continues to show them again and again as duplicates (even if they have 0 instances and are in 0 overrides).

Still working on it :)

**Comment by oodesign** [comment]
And finally... here it is! 

We just released v3.0.4, which fixes the above described issue and shows where the symbol comes from in a clear way.

Try it out and let us know how did it work for you!

Thanks!
