### ISSUE TITLE
Merge layer styles not working

### ISSUE THREAD

**Issue by hiyaneko** [oodesign/merge-duplicate-symbols#130]
Hello, I've written before about the layer and text styles merge not working.. Every time I try to merge styles sketch crashes, it also duplicates several times the styles even tho they come from the same library.
I'm using abstract with a working linked library.

![Screenshot 2020-11-17 at 14 37 18](https://user-images.githubusercontent.com/32107480/99396880-92782780-28e2-11eb-9361-bf786ce39f8f.png)

<img width="1617" alt="Screenshot 2020-11-17 at 10 07 01" src="https://user-images.githubusercontent.com/32107480/99396687-55ac3080-28e2-11eb-9b4d-909b0244f081.png">

**Comment by oodesign** [comment]
Hi @hiyaneko ,

This is an active issue we're actively working on.
You may find more details on [Issue 113](https://github.com/oodesign/merge-duplicate-symbols/issues/113).

Thanks for sending us these details!

**Comment by hiyaneko** [comment]
Great thank you!
