### ISSUE TITLE
Batch merging

### ISSUE THREAD

**Issue by RaphyRaph** [oodesign/merge-duplicate-symbols#14]
With libraries, you're very likely to merge symbols in bulk.
It would be great to inspect all duplicate symbols in a list and select which version to keep like so:

## duplicate symbol A
[x] version 1 - (library A)
[ ] version 2 - (library B)
[ ] version 3 - local
[ ] skip

## duplicate symbol B
[x] version 1 - (library A)
[ ] version 2 - (library B)
[ ] version 3 - local
[ ] skip

... and so forth

**Comment by oodesign** [comment]
Hi Raphaël!

We're currently tracking interest in this very same feature. If we do implement this functionality, we will be back in touch to let you know :)

Thanks for your suggestions, we really appreciate them!

**Comment by oodesign** [comment]
Hi @RaphyRaph,

We've been working on several approaches for this batch merging concept, but it's really hard to ensure merging works fine there are dependencies (when the result of a merge affects another merge that is about to happen down the chain).

So for now we won't be implementing this feature. Thanks a lot for the idea though, it was a good one!
