### ISSUE TITLE
Sketch kept crashing so I reinstalled sketch and now it says my license is already used

### ISSUE THREAD

**Issue by jpm1475** [oodesign/merge-duplicate-symbols#143]
![Merge_duplicates](https://user-images.githubusercontent.com/23405932/108276065-3ae99200-7145-11eb-86d4-fd8430ee97f6.png)
Sketch kept crashing on me so I had to remove everything and reinstall a number of times and now I can't use the same license on the same machine? Please advise, if I can not use the same license on the one and only machine it was installed on I want a refund.

**Comment by oodesign** [comment]
Hi @jpm1475 ,

I'm sorry you're having a bad experience with the activation process. And no, no need at all to get any new license to use it in the same device 😊 .

May you please send us an e-mail with your license key (or the e-mail you used for your purchase on Gumroad)? 
I'll be happy to check it for you, and continue the conversation from there.

Thanks for reaching out!

**Comment by jpm1475** [comment]
07C465D4-76E745D9-947D8022-1D621B5A

My license is associated with this ema

**Comment by oodesign** [comment]
Hi @jpm1475 ,

I've reached out to you via private email, so that we can continue the conversation there. 
I'm closing the issue on GitHub, but please feel free to reopen it if the issue persists, or want to add further detail 😊 .

Thanks!
