### ISSUE TITLE
Plugin doesn't respond at all (Sketch Version: 72)

### ISSUE THREAD

**Issue by cheyneosy** [oodesign/merge-duplicate-symbols#148]
Today Sketch came out with their newest update (Version 72). 

When I tried to merge duplicated symbols, the interstitial window didn't appear. I tried shutting down sketch multiple times, as well as restarting my computer and still nothing. Just wanted to reach out and note that there may be a compatibility issue.

**Comment by interactionmx** [comment]
Same here,  I depend on the plugin for work and it's not working with the latest updates, would appreciate a fix soon

**Comment by YA-GAP** [comment]
me too, updated to version 72 and the plugin does not fire up at all. looking forward 🙏  thanks

**Comment by oodesign** [comment]
Hi @cheyneosy @interactionmx @YA-GAP ,

We just released v8.3.2, which hopefully will fix this issue.
May you please update and tell us how it worked for you?

Thanks!

**Comment by YA-GAP** [comment]
It works again 😊👏👍thx for your speedy response, big fan guys, appreciate that!
lg, YA

————————————————

GRUPPE AM PARK
buchegger, denoth
haslinger, keck


Hr. Yuhsuke Akamatsu 
(gesprochen: Juske)
Head of Digital

Schillerstraße 1 | 4020 Linz
T +43 732 21 66 21-75
M +43 676 786 586 4
***@***.***
www.gruppe-am-park.at

————————————————

Am 06.05.2021 um 14:25 schrieb Oscar Oto ***@***.***>:


Hi @cheyneosy <https://github.com/cheyneosy> @interactionmx <https://github.com/interactionmx> @YA-GAP <https://github.com/YA-GAP> ,

We just released v8.3.2, which hopefully will fix this issue.
May you please update and tell us how it worked for you?

Thanks!

**Comment by cheyneosy** [comment]
Thank you so much :) Everything works again, appreciate the quick turnaround.
