### ISSUE TITLE
Merging duplicate styles breaks link

### ISSUE THREAD

**Issue by mahblahblah** [oodesign/merge-duplicate-symbols#149]
If I have a sketch file that links to a style in my library, and when I merge that library style with another, I would expect that the style in my sketch file would then be linked to the merged style. I am not finding this to be the case. It breaks its link completely. 

I would _assume_ the behavior should be that if I merge 2 styles that everything linked to either of those styles now links to the 1 merged style. Is this assumption wrong?

**The 2 layer styles I want to merge**
<img width="647" alt="Screen Shot 2021-05-11 at 9 55 16 AM" src="https://user-images.githubusercontent.com/49312067/117837854-69a46f80-b23f-11eb-879d-f6765c548c62.png">

**The 2 layer styles being used in my sketch file**
<img width="516" alt="Screen Shot 2021-05-11 at 9 56 26 AM" src="https://user-images.githubusercontent.com/49312067/117838014-8d67b580-b23f-11eb-82e6-35b1f79acb13.png">

**Merging the 2 layer styles (blue into green)**
<img width="1198" alt="Screen Shot 2021-05-11 at 9 56 54 AM" src="https://user-images.githubusercontent.com/49312067/117838081-9fe1ef00-b23f-11eb-89d4-4ccd68116d26.png">

**The styles not respecting the merge in my sketch file**
<img width="531" alt="Screen Shot 2021-05-11 at 9 57 25 AM" src="https://user-images.githubusercontent.com/49312067/117838136-ac664780-b23f-11eb-9f58-b8bcbae1aae3.png">

**Style now unlinked from library altogether**
<img width="284" alt="Screen Shot 2021-05-11 at 9 57 30 AM" src="https://user-images.githubusercontent.com/49312067/117838232-c56ef880-b23f-11eb-85d7-066e9af5aee4.png">

**Log**
`'----- Merge duplicate layer styles -----'
'Finding duplicate layer styles. Including libraries:false'
'-- Found 1 instances, 0 overrides, and created 2 thumbnails'
'Webview loaded'
'WV - Drawing duplicate styles list'
'WV - Drawing left panel style list'
'WV - Drawing styles'
'WV --- Drawing style: 10 Gradients/Positive Gradient'
'WV --- Drawing style: 10 Gradients/Positive Gradient'
'WV - Completed drawing styles'
'WV - Style clicked. Updating selection status.'
'WV - Drawing duplicate styles list'
'WV - Drawing left panel style list'
'WV - Drawing styles'
'WV --- Drawing style: 10 Gradients/Positive Gradient'
'WV --- Drawing style: 10 Gradients/Positive Gradient'
'WV - Completed drawing styles'
'WV - Execute merge'
'Executing Merge'
'-- Merging 10 Gradients/Positive Gradient'
'-- Starting Merge Layer Styles (2). Style to keep is:0'
'---- Processing styles to remove'
'---- Getting all related styles instances and overrides'
'------ Checking if symbol to merge is foreign'
'---- Updating overrides (0)'
'---- Updating instances (0)'
'---- Finalized instance and override replacement.'
'---- Removing discarded layer styles (1).'
'------ Removing 10 Gradients/Positive Gradient (DDEA8F80-12E2-44C0-88E5-D501CB1B46A6) from sharedLayerStyles.'
'-------- Unlinked from library.'
'-------- Located in sharedLayerStyles (96).'
'-------- Removed from sharedLayerStyles.'
'---- Merge completed.'
'Completed merge. Removed 1 layer styles.'
`

**Comment by oodesign** [comment]
Hi @mahblahblah ,

Glad you found it :)
Also please let us know if you have any further doubt or issue with it. 

Thanks for reaching out!
