### ISSUE TITLE
Plugin cause Sketch 72 display crash window on start.

### ISSUE THREAD

**Issue by ozgurgunes** [oodesign/merge-duplicate-symbols#151]
When plugin installed, Sketch displays crash window on start. Sketch runs normal if plugin deleted or disabled. Tested multiple times.
<img width="683" alt="Screen Shot 2021-05-12 at 23 23 00" src="https://user-images.githubusercontent.com/108093/118039706-4ed61600-b379-11eb-8f14-6faac3bd0b26.png">

**Comment by oodesign** [comment]
Hi @ozgurgunes ,

I'm sorry Merge Duplicates is not working well for you. 

May I ask for some further detail about the issue?

- Which MacOS and Sketch version are you on?
- Which MergeDuplicates version are you using? Current version is [v8.3.3](https://github.com/oodesign/merge-duplicate-symbols/releases/tag/v8.3.3). If you're on an older version, does updating help with the issue?

Thanks!

**Comment by ozgurgunes** [comment]
Hi. 

I'm using the updated plugin (v8.3.3) on Big Sur 11.3 (Intel).

Thanks.

**Comment by ozgurgunes** [comment]
I also noticed that I'm facing a license problem. No computer or Sketch license changed. Just did a clean install. I reported the problem and license key to support by email.

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/108093/118102063-fc304480-b3e0-11eb-870f-5e906a40e9b3.png">

**Comment by oodesign** [comment]
Hi @ozgurgunes ,

I've sent you a separate e-mail related to the license.

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit and relaunch the app).
6. Logs will be stored by this point. May you please [send us](mailto:support@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by ozgurgunes** [comment]
Hi, I just sent the plugin logs by email. I'm also pasting the log file contents here. I know there are other plugin errors in the log but the problem occurs only when Merge Duplicates installed and Sketch starts normal when Merge Duplicated only deleted or disabled.

BTW, no need to run any plugin command to produce the problem. It just cause Sketch to display crash window on start.

Thanks.

```
Could not read image data at /Volumes/Ozgur/Dropbox/Works/Library/Extensions/Sketch/Plugins/Sketch-Isometric.sketchplugin/Contents/Resources/https:/github.com/sureskumar/sketch-isometric/raw/master/assets/logo.png
SymbolNameAutocompletePluginController Enabled
✅ loadFramework: `overflowSketchPanel` success!
TypeError: undefined is not an object (evaluating 'sketch_dom__WEBPACK_IMPORTED_MODULE_3__["Document"].getSelectedDocument().selectedLayers')
    at onSelectionChanged (/Volumes/Ozgur/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Overflow.sketchplugin/Contents/Sketch/__main.js:8344:96)
    at onStartup (/Volumes/Ozgur/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Overflow.sketchplugin/Contents/Sketch/__main.js:8331:23)
    at __skpm_run (/Volumes/Ozgur/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Overflow.sketchplugin/Contents/Sketch/__main.js:8530:19)
    at __skpm_run[native code] (/)
ReferenceError: Can't find variable: MSApplicationMetadata
    at /Volumes/Ozgur/Dropbox/Works/Library/Extensions/Sketch/Plugins/PuzzlePublisher.sketchplugin/Contents/Sketch/cmd-actions.js:557:44
Could not read image data at /Volumes/Ozgur/Dropbox/Works/Library/Extensions/Sketch/Plugins/Sketch-Isometric.sketchplugin/Contents/Resources/https:/github.com/sureskumar/sketch-isometric/raw/master/assets/logo.png
'Sketch version:72.1'
'Merge Duplicates version: 8.3.3'
'License: Single'
'----- Merge duplicate symbols (with the same name) -----'
'Local symbols: 0. Library symbols:5670. Document instances:0. Libraries enabled:true'
'Webview called'
'Webview loaded'
'WV - Get symbols'
'WV - Show progress'
'Processing duplicates. Include libraries: true'
'Getting symbols map'
'-- Found 0 duplicates'
'End of processing duplicates'
'Drawing duplicates to webview'
'WV - Drawing duplicate symbols list'
'WV - Hide progress'

```

**Comment by oodesign** [comment]
Hi @ozgurgunes ,

Oh, I feel like we misunderstood the issue you are describing.
Just to clarify (for us 😅). Are the following statements right?

- The crash window appears if you quit (and reopen) Sketch while Merge Duplicates is installed and active. 
- It doesn't if you uninstall or disable the plugin in your Preferences window.
- Despite the Sketch crash dialog, Sketch works fine, (and Merge Duplicates works fine, and everything els works fine).

Is that right?

Thank you!

**Comment by ozgurgunes** [comment]
Yes. This!

**Comment by oodesign** [comment]
Hi @ozgurgunes ,

We just published v8.3.4, which hopefully fixes this issue.
May you please give it a try and let us know how it worked for you?

Thanks!

**Comment by ozgurgunes** [comment]
It works. Thanks a lot.

**Comment by oodesign** [comment]
Thanks for pointing it out @ozgurgunes! Good catch! 🥰
