### ISSUE TITLE
Not able to update 

### ISSUE THREAD

**Issue by SLandstedt** [oodesign/merge-duplicate-symbols#152]
I am not able to update Merge duplicates from 8.3.2 to 8.3.4 using sketch plugins update popup. When I try updating nothing happens.

**Comment by oodesign** [comment]
Hi @SLandstedt ,

I'm afraid we can't reproduce the issue you describe.
Are you able to download [the latest version](https://github.com/oodesign/merge-duplicate-symbols/releases/tag/v8.3.4) from GitHub and install it manually (double click on the .sketchplugin file) ?

Thanks!

**Comment by oodesign** [comment]
Hi @SLandstedt ,

Are you still experiencing this issue?

Thanks!

**Comment by SLandstedt** [comment]
Hello,

Sorry for not updating. The issue was fixed after I followed your
instructions. Thank you very much.

**Comment by SLandstedt** [comment]
I have this problem again with nothing happening when I try to update from inside Sketch.

**Comment by oodesign** [comment]
Hi @SLandstedt ,

This is a bit unexpected. The plugin seems to be properly packaged and updating fine on our end.

Have you also had issues updating to v8.3.5 or v8.3.6? 
Do other plugins update properly?

As a workaround, are you able to get the [latest version](https://github.com/oodesign/merge-duplicate-symbols/releases/tag/v8.3.7) (v8.3.7) and install it manually?

Thanks!
