### ISSUE TITLE
Please give us an additional response to the refund.

### ISSUE THREAD

**Issue by hahohi** [oodesign/merge-duplicate-symbols#154]
I sent my license key to **licensing@oodesign.me** as you requested, but I didn't get a response.
Please tell us about the current progress.

https://github.com/oodesign/merge-duplicate-symbols/issues/153

**Comment by oodesign** [comment]
Hi!

I believe this issue has already been addressed via mail, so I'm closing this issue.
Otherwise please feel free to reopen it :)

Thanks!
