### ISSUE TITLE
Long style names not visible

### ISSUE THREAD

**Issue by Salesbook-design** [oodesign/merge-duplicate-symbols#155]
When working with long style names we encounter the following problem:
Long layer names listed on the left panel are not visible, we can't resize the panel or scroll the content horizontal.
Is there a way to fix this problem?
Thanks
<img width="582" alt="Screenshot 2021-05-25 at 12 00 19" src="https://user-images.githubusercontent.com/84774381/119479414-e3b11a00-bd50-11eb-8359-54cef6f8a24f.png">

**Comment by oodesign** [comment]
Hi @Salesbook-design ,

We're working on this one. I'll make sure to let you know when it makes it to release :) 

Thanks for the feedback!

**Comment by sgxwrk** [comment]
Any progress here on this issue?
Happy to hear from you ✌️

**Comment by oodesign** [comment]
Hi @Salesbook-design and @sgxwrk ,

We just released v8.5.1, that does allow to resize the left side panel.
Could you check it out and let us know how it worked for you?

Thanks!

**Comment by sgxwrk** [comment]
I made a quick test and it works 👍 
(no long term experience)

**Comment by oodesign** [comment]
Awesome, thank you!
I'm closing this issue, but please feel free to reopen it (or create a new one) if you encounter issues again with it. :)
