### ISSUE TITLE
Merge Color variables (From list) not working anymore

### ISSUE THREAD

**Issue by FedericoPagnoni** [oodesign/merge-duplicate-symbols#156]
If i select 2 colors and I try to merge, I got a message error (Sketch unexpected quit)
Sketch is still working, the plugin is not

Sketch Version 72.1
OS Big Sur 11.3.1

**Comment by oodesign** [comment]
Hi @FedericoPagnoni ,

I'm afraid we can't reproduce this issue you describe.
Could you please send us a Sketch file you can reproduce it with? 
Are both color variables local, or some of them is coming from an external library?

Thanks a lot for your help! 🥰
