### ISSUE TITLE
Licence problem

### ISSUE THREAD

**Issue by robsonrobi** [oodesign/merge-duplicate-symbols#158]
We are using your plugin with a two system licence. Switching now to a new computer we cannot activate the licence. The old computer is formatted. Can you please contact and help me?

**Comment by oodesign** [comment]
Hi @robsonrobi ,

We are trying to keep this space for technical issues related with the plugin.
May I ask you to[ send us an e-mail ](mailto:licensing@oodesign.me)with your license key (or the e-mail you used to complete the purchase on Gumroad), and continue the conversation from there?

Thanks for reaching out! 😊
