### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by DieEgg** [oodesign/merge-duplicate-symbols#16]
HI! I've found this plugin super interesting and I've started using it a lot. :)
Unfortunately, it suddenly stopped working some days ago.
I've tried to uninstall and re-install it, but nothing changed: whan I launch the "Merge Duplicate Symbol" command from the menu (or via Sketch Runner), nothing happens - and I'm sure there are symbol in my file that can be merged.
How can I fix it??

**Comment by oodesign** [comment]
Hello Diego!

May I have any more clues about your design file, such as if it's working with symbols from other Libraries?

Would it be possible to have a copy (or a simplified version) of the Sketch file so that I can dig a bit deeper and test it on my own?

Thanks!

**Comment by DieEgg** [comment]
Unfortunately, the file is restricted by NDA, I can't send it to you :(

It doesn't use shared Libraries or similar, it only has its page of symbols. It has actually about 140 symbols in it. The only interaction with symbols not generated in this specific file is: sometimes we 'fork' the file making a copy of it because a colleague has to work contemporarily on some sections, then we merge the file again, so some symbols may come from two copies of the same file.

 I've just noticed that the plugin is still working in other files, but not in this one!

**Comment by oodesign** [comment]
Can you create a new Sketch file, copy some of the symbols that you know that are duplicated (with the same name), and launch the plugin? Just to try if there's something wrong with the Sketch file itself...

Another thing that happened to us some time ago is that, at some point, symbol names got "corrupt" (with special and non-visible characters), and that makes the plugin not recognize them as equal. You could try to rename manually some of the duplicated symbols (just rename them from scratch) and launch the plugin again.

By the way, you can open the "Run script" window in Sketch (ctrl+shift+k, or you may find it in the Plugins menu), and try to compare both names with this little piece of code:

var symbolName1 = "Fields/LoginField"; <-- replace this string with the symbol name (copy/paste it from your symbol)
var symbolName2 =  "Fields/LogniField"; <-- replace this string with the other symbol name (copy/paste it from your symbol)
log(symbolName1.localeCompare(symbolName2));

If it returns 0 it means they're equal. Oherwise... not :)
If they're equal, the plugin should recognise them and ask you to merge. If it doesn't, please tell me.
(The plugin makes a more complex name comparison, but this trial may give us some clues).

**Comment by oodesign** [comment]
Hi Diego!

Did you make any progress with this issue?
Would it be possible to send us a Sketch file with just the symbols that are causing the issue?
You may replace its real content by dummy rectangles, if you wish to.

Thanks!
