### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by CharlesFo** [oodesign/merge-duplicate-symbols#162]
Hello!

I have a problem with my merge copy license.
Would you please take a look at my email and reply to me as soon as possible?
Thank you very much.

**Comment by shylocked** [comment]
The same problem happened to me.

**Comment by oodesign** [comment]
Hi!

We're trying to keep this space for technical issues related with the plugin.
For license issues, may you please [drop us an e-mail](mailto:licensing@oodesign.me), so that we can continue the conversation there?

Thank you!

**Comment by howot090** [comment]
There is no way in the plugin to deactivate a license so I can switch it to another device.
