### ISSUE TITLE
Merge duplicate color variables not working

### ISSUE THREAD

**Issue by Andrii-atom** [oodesign/merge-duplicate-symbols#164]
Hi @oodesign!
I'm having some issues with color variables.

OS: macOS Big Sur 11.3
Merge duplicate 8.5.1

I've tried all the options (duplicate, similar and from list) and it fails the same way with every option. When I click the "Merge color variables" button after I've selected which color variables I want to merge, I get a loading spinner, then it goes back to the plugin window, as If I never clicked the "Merge color variables" button.

The log file enabled but it isn't creating. So the logs folder has no com.bohemiancoding.sketch3/ subfolder in it

**Comment by oodesign** [comment]
Hi @Andrii-atom ,

We just released v8.5.2, that fixes an issue that could cause Merge color variables to fail if there were Hotspots present in the document. May that be your case?

Could you update (Sketch should prompt you to update the plugin, as always) and let us know if this new version works better for you?

Thanks!
