### ISSUE TITLE
Can't merge color variables.

### ISSUE THREAD

**Issue by hanweizUX** [oodesign/merge-duplicate-symbols#166]
Clicking on the "Merge Duplicate" button when using any of the color variable functions won't give any response at all. The cursor will show the loading symbol for a few seconds then nothing happens. The window and selections stay the same.

Layer Styles and other functions are working properly. My license email is henry95918@gmail.com.

**Comment by oodesign** [comment]
Hi @hanweizUX ,

We just released v8.5.2, that fixes an issue that could cause Merge color variables to fail if there were Hotspots present in the document. May that be your case?

Could you update (Sketch should prompt you to update the plugin, as always) and let us know if this new version works better for you?

Thanks!
