### ISSUE TITLE
Liscense key not valid

### ISSUE THREAD

**Issue by multiplemasters** [oodesign/merge-duplicate-symbols#167]
Need to update my plugin for sketch but says my license key isnt valid

**Comment by oodesign** [comment]
Hi @multiplemasters ,

Could you please [send us an email](mailto:support@oodesign.me) with your license key (or the email account you used to acquire your license on Gumroad), so that we can continue the conversation from there?

Thank you!

**Comment by oodesign** [comment]
We're addressing this issue via mail, so I'm closing the issue here 😊 .
