### ISSUE TITLE
Merging Color Variables won't merge - Sketch crashes

### ISSUE THREAD

**Issue by KimRenicke** [oodesign/merge-duplicate-symbols#168]
Dear Developer Team, we are currently working with your newest version of Merge Duplicates. If we're trying to merge color variables with a library the program crashes or the plugin window doesn't respond (doesn't respond to clicking on "Merge Color Variables" Button). Sadly, since the program crashes or doesn't respond, we couldn't find any logs regarding this bug/error/problem. Layer Styles and other functions seem to be working properly. If you need any other information, please let me know.

Thank you in advance!

**Comment by oodesign** [comment]
Hi @KimRenicke ,

I'm afraid we can't reproduce this issue you describe.
Could you please [send us a Sketch file](mailto:support@oodesign.me) you can reproduce it with? 
Are both color variables local, or some of them is coming from an external library?

Thanks a lot for your help! 🥰

**Comment by KimRenicke** [comment]
Hey @oodesign , thank you for the quick response. Sadly, i cannot send you our design and library file due to safety reasons, since we are working for a client. 

I am trying to merge the Color Variables from our Design Document with the existing Color Variables from the Library Document. At this point of time, two documents are linked with the library. We expirience this issue in other projects as well, if there are more than one document linked with the library. In the "merge Color Variables" window I can see everything properly, I can select the desired Color Variables . I can click the "Merge duplicates" button, but nothing seems to happen. My colleauge's Sketch software just crashes, if she tries to merge them. 

I hope this is enough information. I'm sorry I couldn't send you the documents.

Thank you for your time!

**Comment by oodesign** [comment]
Hi @KimRenicke ,

We just released v8.5.2, that fixes an issue that could cause Merge color variables to fail if there were Hotspots present in the document. May that be your case?

Could you update (Sketch should prompt you to update the plugin, as always) and let us know if this new version works better for you?

Thanks!

**Comment by KimRenicke** [comment]
Hey @oodesign!

Thank you so much! It worked!

Have a great day and thank you for your support on this matter :)
