### ISSUE TITLE
Save overrided data while merging

### ISSUE THREAD

**Issue by nickostyle** [oodesign/merge-duplicate-symbols#17]
Hey!

Please make this plugin save overidded data white merging, after that this plugin becomes the best in my collection :-D

Its because you notice duplicates after some time when all instances were overidded, and this plugin merging duplicates removes all data, like if I just replaced by. 

Please, let me know what you think about that. Thanx!

**Comment by oodesign** [comment]
Hi!

Symbol overrides should be kept, as long as the "new" symbol layer name is the same as the one that was overridden in the first symbol.

If it's not working for you, may you provide us some further detail, or a simplified version of the Sketch file so that we can test it on our own?

Thanks!

**Comment by nickostyle** [comment]
Thanx for quick response!

I have checked now, all three symbols have the same layers name, they are completely the same. 
Your plugin shows me three symbols, each one has some quantity of instances but no one has overrides (I didn't understood what does it mean, cause all of them have overrides). And there are some diffiulties in how to chose what symbol keep...

**Comment by oodesign** [comment]
Hi!

The overrides counter stands for how many times this symbol is being used as an override in some other layer or symbol (and not as a direct instance). It doesn't mean that the symbol contains layers or texts that are being overridden somewhere else. We probably need to be more clear on that :) 

Would it be possible to send us a Sketch file with just the symbols that are causing the issue?
You may replace its real content by dummy rectangles, if you wish to. We only need the symbols and its names.

Thanks!
