### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Windinapril** [oodesign/merge-duplicate-symbols#171]
我的激活码不正确？

**Comment by dolbyds** [comment]
Hi @Windinapril ,

I believe we're addressing this issue via support mail, so I'm closing it here, but please feel free to reopen it (or create a new one) otherwise.

Thank you!

**Comment by oodesign** [comment]
Hi @Windinapril ,

I believe we're addressing this issue via support mail, so I'm closing it here, but please feel free to reopen it (or create a new one) otherwise.

Thank you!
