### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by ekimgnaw** [oodesign/merge-duplicate-symbols#172]
I'm switching laptops and my license won't move over. The disclaimer says "All seats are busy!"

I've removed the plugin from my old laptop, but still have the same issue. How do I get my license on the new laptop w/o having to purchase a new license?

I've already written an email to your contact us link — No reply
I've also sent an email to oscar@oodesign.me — Send just before this thread. 

Any assistance is appreciated. 

TY

**Comment by oodesign** [comment]
Hi @ekimgnaw ,

I believe we're addressing this via email, so I'm closing the issue, but please feel free to reopen it otherwise.

Thank you!
