### ISSUE TITLE
Merge colour variables

### ISSUE THREAD

**Issue by MethodBuzz** [oodesign/merge-duplicate-symbols#175]
Interface shows duplicates correctly but merging doesn't work

**Comment by oodesign** [comment]
Hi @MethodBuzz  ,

I'm afraid we can't reproduce this issue you describe 🙈 .
Could you please [send us a Sketch file](mailto:support@oodesign.me) you can reproduce it with? 
Are color variables local, or some of them are coming from an external library?

Thanks a lot for your help! 🥰

**Comment by oodesign** [comment]
Hi @MethodBuzz ,

Does this issue still persist?

Thanks!
