### ISSUE TITLE
I have not received confirmation

### ISSUE THREAD

**Issue by hidalgutzu** [oodesign/merge-duplicate-symbols#178]
I just bought the product with the Paypal option and I have not received a confirmation email. My email: hidalgutzu@gmail.com

**Comment by oodesign** [comment]
Hi @hidalgutzu ,

We're trying to keep this forum for technical issues related with the plugin. 
Could you please [send us an email](licensing@oodesign.me) so that we can continue the conversation there?

Thanks!
