### ISSUE TITLE
Doesn't work certain Sketch files of mine

### ISSUE THREAD

**Issue by tosfan4ever** [oodesign/merge-duplicate-symbols#18]
Here's the file with just my symbols.
[Merge Plugin Doesn't Work.zip](https://github.com/oodesign/merge-duplicate-symbols/files/1785264/Merge.Plugin.Doesn.t.Work.zip)

**Comment by oodesign** [comment]
Hi! I ran the plugin in the Sketch file you attached, and it finds just one duplicate - a symbol called "Row/Numbers" (check the attached screenshot).

Is it the only one that is duplicated? 
Isn't the plugin finding that symbol when you run it in your Sketch?
![im01](https://user-images.githubusercontent.com/11992834/37066356-61a63058-21a5-11e8-800c-02307d9441fe.JPG)

Thanks!

**Comment by tosfan4ever** [comment]
For me however, when I try to run the plugin, it doesn't even work. Nothing happens.

**Comment by tosfan4ever** [comment]
Okay weirdly enough, it works now.

**Comment by oodesign** [comment]
Cool! And... not cool at the same time :)
Any clues about what the issue was?

**Comment by kevinyun** [comment]
I appear to be getting the same issue as well. Running the plugin and nothing happens. Seems to have stopped working after the last update or 2

**Comment by oodesign** [comment]
Hi!

May we have any more clues about your design file, such as if it's working with symbols from other Libraries?

Would it be possible to have a copy (or a simplified version, with just the symbols but no real content) of the Sketch file so that we can dig a bit deeper and test it on our own? 

Thanks!
