### ISSUE TITLE
Crashes as soon as I hit Merge Styles

### ISSUE THREAD

**Issue by followleohans** [oodesign/merge-duplicate-symbols#186]
It's consistent. It always crashes. Running on MacOS Ventura (up to date) on a M1 MacbookPro

**Comment by oodesign** [comment]
Hi @followleohans ,

I'm sorry you're having a bad experience with Merge Duplicates 🙈.

Could you please [send us a Sketch file (or/and libraries)](mailto:support@oodesign.me) you can reproduce it with? 

All files are and will remain confidential, but if you don't feel like sharing your original file (and related libraries), please duplicate your files and remove anything that you don't feel comfortable sharing. As long as the plugin issue still occurs when working with the "simplified" file, we should be able to reproduce it as well.

Thanks a lot for your help! 🥰

**Comment by oodesign** [comment]
Hi @followleohans ,

Thanks for sending us the file. We confirm we can reproduce the issue on our end, and are already working on a fix.
I'll make sure to keep you posted on this 😊.

Thank you!

**Comment by followleohans** [comment]
Hi Oscar
This is just to let you know another user posted the same issue in the Sketch forum today.

All the best,
Leo
￼
∴
Leonardo Hancevich

***@***.*** ***@***.***>
+54 9 11 5578-0146

“No hay nada noble en ser superior a otra persona;
la verdadera nobleza radica en ser superior a tu antiguo yo.”
– Ernest Hemingway

**Comment by followleohans** [comment]
Hi
I wonder if there is an estimated release bug for the fix.
I couldn’t use the plugin since I bought it
All the best,
Leo
∴
Leonardo Hancevich

***@***.*** ***@***.***>
+54 9 11 5578-0146

“No hay nada noble en ser superior a otra persona;
la verdadera nobleza radica en ser superior a tu antiguo yo.”
– Ernest Hemingway

**Comment by oodesign** [comment]
Hi @followleohans ,

We just released v8.5.3, that should hopefully address this issue.
Could you please update (Sketch should trigger a notification automatically) and let us know how it works for you?

Thank you! 🥰

**Comment by followleohans** [comment]
Great news!
I’m a new user, so I couldn’t test it too much, but it appears to work now.

Let me ask you about Mesh gradients for Sketch
Since it can’t export CSS, is it usfeul for UI design too or just for graphic design?
Even with the 50% its a little expensive for me right now (for exchange reasons since I’m in Argentina), but I wonder if I should make the effort anyway for that.

All the best
Leo

∴
Leonardo Hancevich

***@***.*** ***@***.***>
+54 9 11 5578-0146

“No hay nada noble en ser superior a otra persona;
la verdadera nobleza radica en ser superior a tu antiguo yo.”
– Ernest Hemingway

**Comment by oodesign** [comment]
Hi @followleohans ,

I'm closing the issue as I apparently has been addressed, but please feel free to reopen it otherwise.

Thanks! 🥰
