### ISSUE TITLE
License key is not valid

### ISSUE THREAD

**Issue by 493074313** [oodesign/merge-duplicate-symbols#187]
I purchased this plugin on the morning of April 13th, 2023, but the registration code sent to my email cannot be used as it shows "cannot be used".

**Comment by 493074313** [comment]
<img width="756" alt="截屏2023-04-13 11 19 02" src="https://user-images.githubusercontent.com/12985848/231641079-0764b852-fd59-4b3a-ac19-f797d641e58e.png">

**Comment by 493074313** [comment]
email adress ：493074313@qq.com

**Comment by oodesign** [comment]
Hi!

I've reached out via mail to hopefully address this issue.
As it is related to account and subscription (and wouldn't like to disclose any personal data here), I'd suggest to continue this conversation in the mail thread. 

I'll also remove the bits that reveal some license or personal information here. Hope that's fine for you :)

**Comment by oodesign** [comment]
I'm closing the issue as I believe has been successfully addressed, but please feel free to reopen it otherwise.

Thanks!

**Comment by 493074313** [comment]
OK , Thank you.
