### ISSUE TITLE
Can't merge duplicate symbols when file is set as Library

### ISSUE THREAD

**Issue by cimaja** [oodesign/merge-duplicate-symbols#19]
Hi guys, when I try to merge duplicate symbols from a file used as a Library the plugin doesn't work. If I copy the duplicate symbols and paste them in a new file and retry to merge them with the plugin it works. See this [video](https://1drv.ms/v/s!Am-EFLU8zBoMiMUxfBfo7IYULE5-Hg) for more détails.

**Comment by oodesign** [comment]
Wow how!

I'm afraid we've never tested the plugin in a Library file, but we sure will!

Thanks for the video, it helps a lot to understand the issue.

I'll let you know when we haver more info about it, or a release that solves it.

Thanks!

**Comment by oodesign** [comment]
Hi!

We just released version 3.0.6, that hopefully would solve some of the issues causing the plugin to do nothing apparently in several situations.

Please, let us know if it did work for you!
