### ISSUE TITLE
如何解绑设备从而激活新的设备

### ISSUE THREAD

**Issue by 1052971551** [oodesign/merge-duplicate-symbols#191]
现我需要将1号激活设备取消激活状态，将这个序列号用于2号设备上，如何操作？

**Comment by 1052971551** [comment]
Now I need to deactivate the No. 1 activation device and use this serial number on the No. 2 device. How to do it?

**Comment by 1052971551** [comment]
我购买了两台设备的许可证，但是我现在无法使用这个许可证了

**Comment by 1052971551** [comment]
I bought a license for two devices, but I can't use this license now.

**Comment by oodesign** [comment]
Hi @1052971551 ,

I believe we're addressing this issue via mail, so I'll be closing this one.
Still, please feel free to reopen if you consider so 😊

**Comment by 1052971551** [comment]
你好，我有个建议，给插件增加一个设备管理功能，这样我就可以自由控制我的许可证用于哪个设备。如果许可证只能激活一台设备且不能更换的话，对于个人来说并不友好，因为购买是一笔不菲的支出

Hi, I have a suggestion to add a device management feature to the plug-in so that I can control which device my license is used for. If the license can activate only one device and cannot be replaced, it is not personally friendly because the purchase is a significant expense
