### ISSUE TITLE
Transfer license

### ISSUE THREAD

**Issue by bytepoets-cha** [oodesign/merge-duplicate-symbols#192]
According to some closed concerns here on Github, it seems to be common that support requests are answered only after a comment here, because the emails before that don't arrive or are at least not responded to. That's why I'm commenting here as well.

I sent a mail to licensing@oodesign.me two days ago that I moved to a new laptop and I can't use the plugin now, because - despite deleting the plugin on the old device - the license is still occupied.

Please check if you've received my email. I look forward to a response to my concern.
Thank you very much.

**Comment by oodesign** [comment]
Hi @bytepoets-cha ,

Our apologies for the late reply. Somehow we missed your previous emails 🙈.

I believe this issue is being addressed by mail now, so I'm closing this issue, but please feel free to reopen otherwise.

Thank you!
