### ISSUE TITLE
Lisence error

### ISSUE THREAD

**Issue by steakyamyam** [oodesign/merge-duplicate-symbols#194]
hello. 
I bought a plugin yesterday But there is a licensing error. 
I sent an email yesterday, but there was no answer, so I leave an inquiry here.
please check my issue.

error message: Looks like the license key is not valid. May you try again? If you think is an error, please contact us

thank you

**Comment by oodesign** [comment]
Hi @steakyamyam ,

I believe this issue is being addressed by mail now, so I'm closing this issue, but please feel free to reopen otherwise.

Thank you!
