### ISSUE TITLE
Transfer license

### ISSUE THREAD

**Issue by mxdslien** [oodesign/merge-duplicate-symbols#195]
Hi,
I see a similar issue here in GitHub, and I'm having the same issue.
I also recently got a new Mac, and would love to move the license to this device. Sent an email about a week ago with no response. Can you help? Thanks!

**Comment by oodesign** [comment]
Hi @mxdslien ,

I believe we're addressing this issue via mail, so I'll be closing this issue here.
However, please feel free to reopen otherwise or if anything else pops up. 

Thanks! 🥰
