### ISSUE TITLE
Merging symbol issues

### ISSUE THREAD

**Issue by futurebreeze29** [oodesign/merge-duplicate-symbols#196]
When I merge 2 symbols with the same name, the command does not work. Furthermore the temp symbol name the pluign creates is left behind
<img width="1064" alt="Screenshot 2023-11-19 at 21 14 06" src="https://github.com/oodesign/merge-duplicate-symbols/assets/92085372/ca4eb369-3008-4bbd-8577-82e1546be3c7">

**Comment by oodesign** [comment]
Hi @futurebreeze29 ,

I'm afraid we can't reproduce the issue you describe with our testing set 🙈 .
Could you please [send us a Sketch file](mailto:support@oodesign.me) you can reproduce it with? 

All files are and will remain confidential, but if you don't feel like sharing your original file (and related libraries), please duplicate your files and remove anything that you don't feel comfortable sharing. As long as the plugin issue still occurs when working with the "simplified" file, we should be able to reproduce it as well.

Thanks a lot for your help! 🥰
