### ISSUE TITLE
Website is very Slow 

### ISSUE THREAD

**Issue by nihalawasthi** [oodesign/merge-duplicate-symbols#198]
Suggest you to switch to react [ expected $200 - $1000 ]
or hire a good developer to rebuild this site in Optimized Html version only [ $20 - $100 ]

**Comment by oodesign** [comment]
Hi Nihal,

Thank you for bringing this to our attention. We appreciate your feedback regarding the website's performance. While we acknowledge that the site may currently be slower than expected, we do not have plans to update it at this time.

We apologize for any inconvenience this may cause and appreciate your understanding.
