### ISSUE TITLE
Feature Request: Display more information while merging

### ISSUE THREAD

**Issue by yinkou** [oodesign/merge-duplicate-symbols#22]
It would be super helpful to display more information per symbol in the merge dialog like:

- artboard size
- page name
- creation date (if possible)

So we can differentiate on more indicators.
Would be really happy to see that!
Thanks for your work, best,
Boti

**Comment by oodesign** [comment]
Hi @yinkou!

We're currently tracking interest about which data could be relevant to show in the plugin to help you decide which symbol to keep. If we do implement this functionality, we will be back in touch to let you know :)

Thanks for your suggestions, we really appreciate them!

**Comment by oodesign** [comment]
Hi @yinkou !

We just added the Page name in every mergeable instance. 
Hope it helps!
