### ISSUE TITLE
Idea: Megre Text Styles Plugin!

### ISSUE THREAD

**Issue by okunev** [oodesign/merge-duplicate-symbols#23]
Hello! Thank you for your plugin. It would be cool if you developed similar plugin to handle text style duplication.

**Comment by oodesign** [comment]
Hi! Maybe Style Libraries plugin would help https://github.com/sigtm/sketch-style-libraries .
But as far as I know, it won't let you decide which style to keep (my guess is that it just merges all styles with same name, keeping the first of them in the "Organize text styles" list).

Also https://github.com/aparajita/sketch-style-master would help you managing its names faster than the native styles manager window.

Let me know how it worked for you, and if you find/use any other plugin for this.
And if it not, let us know anyway... and maybe we can give it a try :)

**Comment by okunev** [comment]
Sketch Style Master doesn't resolve any conflicts. It is just a convenient way to sort existing styles.

**Comment by okunev** [comment]
Sketch Style Libraries does exactly what I need. Thank you so much.
