### ISSUE TITLE
Crashes when merging our color swatch symbols

### ISSUE THREAD

**Issue by pmvogt** [oodesign/merge-duplicate-symbols#26]
Our color symbols from the design system get re-used a TON throughout Sketch files. 

<img width="547" alt="screen shot 2018-06-25 at 12 06 38 pm" src="https://user-images.githubusercontent.com/4655225/41864624-3dfd14c4-7870-11e8-820b-0c18b4e0e355.png">

Here's one such example. It's not uncommon to have 50-100 instances of one of these colors. Reliably, the plugin crashes when attempting to merge them with over ~25-30 instances. This doesn't tend to happen with text symbols with many instances, or other components (pagination controls, whatever). 

The symbol is nothing more than a 96x96 color rectangle. No layer style applied or anything like that.

**Comment by oodesign** [comment]
Hi!

Sad to hear you're having issues with the plugin...

We've been testing on our own with Sketch files with >100 pages and >1000 instances of color swatches and stills works well (a bit slow, that's true :) ).

Would it be possible to have one of those files you work with to run some tests and debugging on our own? Feel free to remove anything that you wouldn't like to share, but keeping the nested symbols or instances...

Thank you!
