### ISSUE TITLE
Feature Request: Merge only selected symbols

### ISSUE THREAD

**Issue by michelluarasi** [oodesign/merge-duplicate-symbols#30]
It would help a lot if the merging can be better controlled by selecting the symbols manually. Right know, we have to go through issue by issue.

**Comment by oodesign** [comment]
Hi Michel!

It's a good point. I'll add it to our backlog and make sure to let you know when it is released :)

Thanks for your feedback!

**Comment by oodesign** [comment]
Just to make sure, @michelluarasi ... do you mean merging selected symbols (even if their name is different)? Or the ones that are selected that do have the same name? 

Thanks!

**Comment by michelluarasi** [comment]
Thank you for the follow up @oodesign.

I usually use the same naming even if there are different color variations. In that case it would be great, if we could select those and merge them individually (check screenshot).

But your point is also good and useful. Merging different symbol names would just mean, that there needs to be some kind of option to select the final name.

![merge-icons](https://user-images.githubusercontent.com/1634004/45434468-d04be680-b6ae-11e8-8559-97e856857204.png)

**Comment by oodesign** [comment]
Hi @michelluarasi !

We just released v4.0.0, that allows designers to merge different symbols, even if their name doesn't match.

May you give it a try and let us know how it worked for you?

Thanks!

**Comment by michelluarasi** [comment]
Now that was fast! I just tested the feature and it works smoothly. It's merging time! ;)

Thanks a lot!
