### ISSUE TITLE
Bring back auto detect instead of only selected symbols

### ISSUE THREAD

**Issue by swizenfeld** [oodesign/merge-duplicate-symbols#32]
the previous version was a lot more helpful to me than having to select symbols

**Comment by oodesign** [comment]
Hi @swizenfeld !

Both options are available now. The classic one, now called "Merge symbols with the same name (all over the document)", scans all document symbols and asks what to do do with each duplicate. It may be triggered from the Plugins menu or by pressoing the CTRL+SHIFT+M shortcut.

The new option is "Merge selected symbols (even if name doesn't match)", and allows you to merge the selected symbols, doesn't matter what their name is. It may be triggered from the Plugins menu or by pressoing the CTRL+OPTION+SHIFT+M shortcut.

Are you having trouble with any of them?

Thanks for getting in touch!
