### ISSUE TITLE
Crashes when merging a specific symbol

### ISSUE THREAD

**Issue by SevenZark** [oodesign/merge-duplicate-symbols#34]
Just started trying to use this plugin today. It seems to successfully get through several merges, but then always crashes Sketch on the same one (image attached). 

![image](https://user-images.githubusercontent.com/426718/53103370-20976200-34f3-11e9-8181-238f6022815a.png)

**Comment by oodesign** [comment]
Hi @SevenZark!

Sorry to hear that.
We're not able to reproduce it with our testing files, though.

May you send us a Sketch file with just the symbols that are causing the issue?
You may replace its real content by dummy rectangles, if you wish to. We only need the symbols and its names.

Thanks!

**Comment by oodesign** [comment]
Hi @SevenZark,

Any updates on this? Still having this issue?

If you do, may you send us a Sketch file with just the symbols that are causing the issue?
You may replace its real content by dummy rectangles, if you wish to. We only need the symbols and its names.

Thanks

**Comment by SevenZark** [comment]
Forgive me, I had to resolve the problem really quickly so I just wound up re-drawing the comps and it fixed the issue. I no longer have an asset I can share which will demonstrate the problem. I will close the issue.
