### ISSUE TITLE
Stops merging after certain amount

### ISSUE THREAD

**Issue by moniquep** [oodesign/merge-duplicate-symbols#38]
For example, the dialogue will say there's 70 symbols to merge, but will finish at 61.

**Comment by oodesign** [comment]
Hi @moniquep ,

Sorry to hear that. Looks like the plugin may be crashing at some point and cannot continue the merging. I'm afraid we're not able to reproduce it with our testing set, though.

May you send us a Sketch file with just the symbols that are causing the issue?
You may replace its real content by dummy rectangles, if you wish to. We only need the symbols and its names.

Also, which Sketch version and plugin version are you using?

Thanks!

**Comment by moniquep** [comment]
Here is a video of the issue and a sketch file. It occurs in all of my
sketch files
https://www.dropbox.com/s/vduf0kwap932o24/merge-symbol-bug.mov?dl=0
These are all the plugins I have installed
[image: image.png]

I just update to the latest version of your plugin, whichever that is and
the issue still exists.
I'm using Sketch 55.

**Comment by oodesign** [comment]
Hi @moniquep,

Thank you for the video! May we assume that after that "2 of 27" the plugin closes up and nothing else happens? Or Sketch freezes in some way? 

Are you able to reproduce always this issue with the same Sketch file? Does it always get stuck in that same symbol? If so, we'd love to have a copy of that Sketch file (with just the symbols that are causing the issue, you can remove everything else if you want) to run some further investigation.

Meanwhile, as a workaround, are you able to select those 2 same symbols and run "Merge duplicate symbols > Merge selected symbols" (the other plugin approach)? Does it merge the symbols, or does it also crash (or don't do anything)?

We can't see the plugin list attached image. May you send it again? 

Thanks a lot! This really helps us!

**Comment by oodesign** [comment]
Hi @moniquep,

We've just released v4.0.8 (v5.0.1 if you purchased the plugin), that fixes an issue that was causing the plugin to crash when trying to merge symbols coming from external libraries. 
May you take a look and let us know how it works for you?

Thanks a lot!
