### ISSUE TITLE
Display Usage Counts

### ISSUE THREAD

**Issue by sonburn** [oodesign/merge-duplicate-symbols#4]
First of all, great plugin. Something I have been thinking of tackling with Symbol Organizer.

Enhancement idea, display usage counts next to each duplicate symbol, to help facilitate the choice of the one to keep. Personally, I am going to try and select the one that is used the most... the others are likely used once or twice.

**Comment by oodesign** [comment]
Hi! Thanks for the feedback!
We're followers and heavy users of Symbol Organizer, so... it means a lot for us.

It's an awesome and (easy to ship) idea. We'll work on it and let you know when it's released :)

Thank you!

**Comment by oodesign** [comment]
Hi!

We just released a new version (2.0.0), which solves some performance issues and displays usage data as you suggested :)

Thanks for the idea!
