### ISSUE TITLE
Manuel Merge for Styles - Elispes Issue

### ISSUE THREAD

**Issue by jansemka** [oodesign/merge-duplicate-symbols#41]
Would be nice to see the full name of the Style :-)

<img width="835" alt="image" src="https://user-images.githubusercontent.com/13254959/58553728-f8b44a80-8215-11e9-80c0-976319805e22.png">

**Comment by oodesign** [comment]
Hi @jansemka,

Absolutely. More room for style names in next version!
There's a tooltip if you hover them (and the title appears on the big cards when style is selected), but obviously not ideal for first selection.

I'm afraid we'll need to set a maxwidth, though... so long long names will be clipped anyway.

I'll make sure to let you know when the next version is released.

Thanks a lot!

**Comment by oodesign** [comment]
Hi @jansemka ,

We just released v5.0.2, that makes more room for the style names. 
Hope it helps!
