### ISSUE TITLE
Nested styles not merging

### ISSUE THREAD

**Issue by mpnak** [oodesign/merge-duplicate-symbols#42]
I have multiple styles listed like icon/dark/default and neither method of merge styles will merge them.

**Comment by oodesign** [comment]
Hi @mpnak,

Just to make sure about the issue. Do you mean that you have several styles called "icon/dark/default/, and "Merge Layer Styles with the same name" is not finding them, and not suggesting you to merge them? If that's the case, if you try to "Merge layer styles (from list)", do they appear there? And if so, are you able to merge them there?

Apart, just a couple of considerations that may be involved in the issue:

Currently, the only styles that are considered for merging are the ones that are in use in your document. So if you have two styles with the same name, but one is not being used anywhere, the plugin won't consider it (maybe we should?).

The other consideration is that the plugin doesn't remove the styles that are coming from external libraries. When merging it will apply the selected style to layers and overrides, but if one of the discarded styles is coming from an external library, it won't get removed.

May any of those two considerations be the cause of your issue?

Thanks!

**Comment by mpnak** [comment]
Yes several styles called “icon/dark/default". Merge Layers doesn’t work with either method. I can see them in the layer list then choose one to merge to, but it’s not working.

I see the issue though is not all the styles are actually in use in the document. 

In order to solve I’ll add another plugin to remove unused styles. It would be nice though if your plugin could merge unused styles as well. That way, when applying that style to future items I only have one in the list to select from.

Thanks for the quick response,

Michael

**Comment by oodesign** [comment]
I see. We'll investigate what may be causing the issue, and I'll make sure to let you know when it's fixed.

We're also considering including all styles in the document (even if they're not in currently use). Our best guess for now is to include all document styles (whether they're in use or not), but for external libraries styles just include the ones that are in use. What do you think?

Thanks a lot!

**Comment by nimbling** [comment]
Just to weigh in on this, I'd need all styles of both the current document and the library, please :)

I have a set of "theme colors" that I'm trying to merge, and I don't have everything in use in either document.

**Comment by oodesign** [comment]
Hi @nimbling ,

Definitely, being able to include all styles (local and external libraries) would help in many situations. We're on it, so stay tuned for updates!

Thank you all for your feedback!

**Comment by oodesign** [comment]
Hi @nimbling and @mpnak ,

We just released v5.0.2, that makes it possible to include external library styles in the merging list, even if they're not in use in the current document. Look for the "Merge styles (from list)" options, and let us know how it worked for you!

Hope it helps!

**Comment by mpnak** [comment]
Excellent. Thanks for the update. I’m going to test it right now!

**Comment by mpnak** [comment]
Working great so far. Thanks for the useful updates!
