### ISSUE TITLE
Single style listed many times.

### ISSUE THREAD

**Issue by nimbling** [oodesign/merge-duplicate-symbols#43]
I'm trying to merge my document styles to the ones in my library, but I get this:

<img width="774" alt="Screenshot 2019-06-03 at 10 53 26" src="https://user-images.githubusercontent.com/821411/58789205-df344980-85ed-11e9-80fe-c2bccd9192d3.png">

In both documents, "---WHITE" is present only a single time.

Here's my files, the "Library" one is set as, yep, the library for the other one.

https://www.dropbox.com/s/cw3wvain0ldc3a6/Fun%20Learning.sketch?dl=0
https://www.dropbox.com/s/mhdt1dql1kapoh4/Squla%20Library.sketch?dl=0

**Comment by oodesign** [comment]
Hi @nimbling ,

Wow, that definitely looks like a bug 😅.
Thank you for handling us those files. We're able to reproduce the issue, and currently working on it. 

I'll make sure to let you know when it's fixed.

Thank you!

**Comment by nimbling** [comment]
How is this going? I'd *really* love to be able to use the plugin I bought ;)

**Comment by oodesign** [comment]
Hi @nimbling ,

We're currently working on this issue. Turned out that what at first sight seemed a bug in the plugin, it was not. Won't get too technical about it, but thing is that from a technical point of view, all of those "---White" styles EXIST actually in the document, so we need to handle them as well.

We're on the testing phase of the fix. As soon as we're able to release a stable update I'll make sure to let you know. 

Thanks!

Thanks for your

**Comment by nimbling** [comment]
Sounds difficult indeed,
keep up the good work!
Thanks :)

**Comment by oodesign** [comment]
Hi @nimbling ,

We need to make some major changes to address this issue. We're in the good direction, but may need some more time to get to a stable release. 

I apologize for any inconvenience this may cause. I'll make sure to let you know when we have a fix for it.

Thank you!

**Comment by nimbling** [comment]
I'm watching this space like a hawk! :) thanks! :)

**Comment by oodesign** [comment]
Hi @nimbling ,

We just released v5.0.2, that hopefully fixes this issue (and many more) and you don't have to deal with internal duplicate styles anymore :) 

Let us know how it worked for you!

**Comment by nimbling** [comment]
IT IS WORKING FOR ME
SORRY FOR YELLING BUT I'M REALLY HAPPY WITH IT
THANK YOU

**Comment by nimbling** [comment]
Ooh! I do have one more (hopefully small) request :)
Currently, the merging defaults to the "current document" one, but for my use case (I'm going through a big list) defaulting to the (lib) version would work faster. Is that a big ask?

**Comment by oodesign** [comment]
Hi @nimbling ,

The merge decision list does not default to any of them currently... you still have to click on one of them to merge. It's just sorted alphabetically, and the document ones get first.

But you're probably right. In the "Merge styles with the same name", in which we have two (or several) styles with the same name, and one of them is coming from a library, I guess the most common decision will be to use the Library one. We could default to the Library one there.

I wouldn't do the same for the "Merge from list" options, though. What's your thought on that?

Thanks a lot for your feedback!
