### ISSUE TITLE
How many users can use through one purchase?

### ISSUE THREAD

**Issue by SDKarthikRaj** [oodesign/merge-duplicate-symbols#44]
Our design team has 5 people. Can we all 5 use the plugin through one purchase?

**Comment by oodesign** [comment]
Hi @SDKarthikRaj ,

We're trying to keep this space just for technical issues related with the plugin.
May I ask you to send me an e-mail to oscar@oodesign.me to address any purchase or invoicing doubt?

Thank you! 😉

Òscar from oodesign
