### ISSUE TITLE
Merge duplicate symbol doesn't show in Runner search

### ISSUE THREAD

**Issue by sirme87** [oodesign/merge-duplicate-symbols#45]
Merge duplicate symbols and merge selected symbol didn't appear in Runner result. Other commands like merge style still appear.

https://i.gyazo.com/543e39370b3845c8cad6b2c7d144680a.gif

**Comment by oodesign** [comment]
Hi @sirme87,

Whoa, that was a mystery 👻!!! Looks like Sketch Runner doesn't like a submenu called just "Symbols" (like Merge duplicates... > Symbols). Maybe a restricted word? 🤷‍♀️

Our best fix for now is just to change that naming, so from now on you will see it as "Merge Duplicates > 💎Symbols", and with this it will appear on your "Run" screen within SketchRunner. 

It will appear on our next release (v5.0.2), that will be launched by the end of this week, so stay tuned for updates!

Thanks a lot for letting us know!

**Comment by oodesign** [comment]
Hi @sirme87  ,

We just released v5.0.2, that makes it possible (again) to run the Merge Duplicates Symbols command directly from Sketch Runner.
 
Hope it helps!
