### ISSUE TITLE
Enlarge the window size of the plugin

### ISSUE THREAD

**Issue by scrapix** [oodesign/merge-duplicate-symbols#46]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/23144020/59034636-b620ec80-886b-11e9-99d5-263ecc66f0b2.png">

Hello, could you please enlarge the window size of your pligin. Especially when merging Text Styles it's hard to see the full name of text styles with loger names.

**Comment by oodesign** [comment]
Hi @scrapix ,

Yes, we're definitely having more space for the style list in the next update! :)
There's a tooltip if you hover them (and the title appears on the big cards when style is selected), but obviously not ideal for first selection.

I'm afraid we'll need to set a maxWidth, though... so long long names will be clipped anyway.

I'll make sure to let you know when the next version is released.

Thanks!

**Comment by oodesign** [comment]
Hi @scrapix  ,

We just released v5.0.2, that makes more room for the style names.

Hope it helps!

**Comment by scrapix** [comment]
Hi @oodesign,

Thank you tons for this quick improvement! 

Best,

S
