### ISSUE TITLE
idea: merge symbols with library file

### ISSUE THREAD

**Issue by andreschauer** [oodesign/merge-duplicate-symbols#48]
hey,

is it possible to merge symbols with a library file?
it would be helpful to be able when splitting an older sketch file to seperate sub files.

thank you!

andré

**Comment by oodesign** [comment]
Hi @andreachauer,

Wow, that'd be super cool 🤩. Not supported now, but may be a good point for a future update.

Thanks a lot for your feedback!

**Comment by andreschauer** [comment]
Hey Oscar,

i have another wish for the plugin:

if you want to merge to symbols without the same name,
you dont know which one is the one already in use
(you can only guess by overrides and instances).
when i want to merge to the right one with the right name,
i always have to mark the right one with a form.


thank you!

andré :)

**Comment by oodesign** [comment]
Hi @andreschauer ,

Oh, I see! What would help you figure out which is the one you want to keep (apart from the data we're already displaying in the merge list)?

Thanks!

**Comment by andreschauer** [comment]
Hey Oscar,

maybe you know it already but i think this plugin would help to select and merge
all Instances of a symbol to one in a library.
maybe you can combine this function in your plugin?

greetings,

andré

**Comment by andreschauer** [comment]
sorry - forgot the link: https://github.com/nmwoods1/Sketch---Find-all-instances-of-symbol <https://github.com/nmwoods1/Sketch---Find-all-instances-of-symbol>

**Comment by oodesign** [comment]
Hi @andreschauer,

Merging symbols (including external libraries) is in our backlog. As soon as we release it I'll be happy to let you know :)

Thanks!

**Comment by oodesign** [comment]
Hi @andreschauer ,

I'm really happy to announce a [brand new Merge Duplicates](https://youtu.be/HZLn2zQMMCI) 🥳, that you can already download straight from [Gumroad](https://gumroad.com/library) or from [GitHub](https://github.com/oodesign/merge-duplicate-symbols).

And to celebrate we arranged [this cool video](https://youtu.be/HZLn2zQMMCI) showing the new cool stuff. Don't miss it out!

It includes...

- Merge symbols from linked libraries ⭐️⭐️⭐️
- Whole brand new UI
- Merge all symbols from a single window
- List and Card view
- Updates back in native Sketch
- And many many more...

Hope you like it! And happy merging!
