### ISSUE TITLE
What does (EXT) mean?

### ISSUE THREAD

**Issue by nimbling** [oodesign/merge-duplicate-symbols#51]
I understand what (lib) means when I'm merging duplicate styles.

Now, after I enable "include all enabled libraries..." some items show with (ext) next to their names. What do they mean?

**Comment by oodesign** [comment]
Hi @nimbling,

A little bit of docs are coming soon, but meanwhile:

- (Lib) means this is a foreign style, coming from an external library, that is currently in use in the document.
- (Ext) means this is a foreign style, coming from an external library, that is currently NOT IN USE in the document.

We should be more explicit about it, but still want to keep things simple and short.
