### ISSUE TITLE
Display name of symbol when merging

### ISSUE THREAD

**Issue by michaelahokas** [oodesign/merge-duplicate-symbols#53]
Currently when merging the name of the symbol isn't displayed which makes it difficult to choose the right one.

![Screen Shot 2019-07-10 at 20 55 54](https://user-images.githubusercontent.com/8209164/60963847-46fc5380-a355-11e9-905e-fdbd765a2a6a.png)

**Comment by oodesign** [comment]
Hi @michaelahokas,

Wow, that sounds so obvious now that you said it!
Not needed when merging symbols with the same name, but totally needed when merging selected symbols. I'll make sure to add it to our next release.

By the way... is there any other attribute that may be helpful to figure out which symbol you want to keep or discard?

Thanks for your feedback!

**Comment by michaelahokas** [comment]
It would be good if it could show the names of the artboards where the instances are used.

**Comment by seltzdesign** [comment]
Any updates on this issue? It seems like such a no-brainer and I always have to guess which one the one is I want to keep.

**Comment by oodesign** [comment]
Hi @seltzdesign ,

Absolutely. We're secretly working 🤫 on an overall UI update for Merge Duplicates, and it may get released within the next couple of weeks, so... stay tuned for updates!

Thanks!

**Comment by oodesign** [comment]
Hi @seltzdesign ,

I'm really happy to announce a [brand new Merge Duplicates](https://youtu.be/HZLn2zQMMCI) 🥳, that you can already download straight from [Gumroad](https://gumroad.com/library) or from [GitHub](https://github.com/oodesign/merge-duplicate-symbols).

And to celebrate we arranged [this cool video](https://youtu.be/HZLn2zQMMCI) showing the new cool stuff. Don't miss it out!

It includes...

- Merge symbols from linked libraries ⭐️⭐️⭐️
- Whole brand new UI
- Merge all symbols from a single window
- List and Card view
- Updates back in native Sketch
- And many many more...

Hope you like it! And happy merging!
