### ISSUE TITLE
Are we buying the plugin or the licence? 

### ISSUE THREAD

**Issue by nikitavergis** [oodesign/merge-duplicate-symbols#59]

**Comment by oodesign** [comment]
Hi @nikitavergis  ,

We're trying to keep this space just for technical issues related with the plugin.
May I ask you to send me an e-mail to oscar@oodesign.me to address any purchase, licensing, or invoicing doubt?

Thank you! 😉

Òscar from oodesign

**Comment by nikitavergis** [comment]
Hi Oscar,

When I clicked on support it opened Github, which is why I posted the
question there. Sorry for the confusion.
Am I buying the plugin or the licence when I buy Merge Duplicates?

- Nikita Vergis

**Comment by oodesign** [comment]
No worries. We should do better at routing differently issues and purchasing doubts. 😅

What you get is a license to use Merge Duplicates. It's a one-time purchase, and all updates are included with it. No subscriptions, and no further surprises :)

The plugin license is per designer. As soon as you complete your purchase, you'll receive a license key that can be used for the number of designers you've purchased it for.

Hope it helps, and please let us know if there's anything else we can help you with.

Òscar from oodesign
