### ISSUE TITLE
!Question

### ISSUE THREAD

**Issue by ktryndchrs** [oodesign/merge-duplicate-symbols#63]
Is there any plan to keep override? Even when the names and property, everything is exactly the same except the override, I lose them... This was the main reason I wanted this plugin.. :/

**Comment by ktryndchrs** [comment]
I made a pdf of the steps I followed and the en result I had... Probably you would tell me to go and send an email to the "Batch Symbols Create" author. However, I think you will be more of a help here...

[merge symbols overrides issue.pdf](https://github.com/oodesign/merge-duplicate-symbols/files/3601070/merge.symbols.overrides.issue.pdf)

**Comment by ktryndchrs** [comment]
This was my though 😭
Thanks for the awesome answer and the plugin (I was not aware of this one!)

Cheers,
Catherine

**Comment by oodesign** [comment]
Glad it helped! 🙂
