### ISSUE TITLE
Transfer lisence to different email

### ISSUE THREAD

**Issue by heywendychu** [oodesign/merge-duplicate-symbols#66]
Hi there, 

I bought your plugin and had it emailed to a work email. I have since left that job and can't access that email, and wanted to transfer it to my personal email. Can you please let me know if that's possible? 

Please email me at seasonalrain@gmail.com

**Comment by oodesign** [comment]
Hi @heywendychu ,

We're trying to keep this space just for technical issues related with the plugin.
May I ask you to send me an e-mail to oscar@oodesign.me with the e-mail you used for the purchase, and the e-mail you want us to update it to?

Thank you! 😉

Òscar from oodesign

**Comment by heywendychu** [comment]
Hi Oscar, Sure thing! I just didn't see a contact email for other support
questions, but will do that right now!

--Wendy
