### ISSUE TITLE
Selected symbol indicator

### ISSUE THREAD

**Issue by oscarubio** [oodesign/merge-duplicate-symbols#67]
When there's only two symbols to merge, it's hard to know which one is selected so maybe a tick or a radiobutton somewhere would help. Something like this:

![selected](https://user-images.githubusercontent.com/23089150/66526686-30ce7280-eabf-11e9-88c1-cb68244a0293.png)

Also, I would use the white bg as the active/selected state, since the contrast is more notable.

**Comment by oodesign** [comment]
Hi @oscarubio ,

Absolutely! We're working secretly 😉on a new version of Merge Duplicates, and that includes many improvements in the UI, so keep an eye on updates!

Anyway, I'll be happy to let you know when this has been released :)

Thanks for your feedback!

**Comment by oodesign** [comment]
Hi @oscarubio ,

I'm really happy to announce a [brand new Merge Duplicates](https://youtu.be/HZLn2zQMMCI) 🥳, that you can already download straight from [Gumroad](https://gumroad.com/library) or from [GitHub](https://github.com/oodesign/merge-duplicate-symbols).

And to celebrate we arranged [this cool video](https://youtu.be/HZLn2zQMMCI) showing the new cool stuff. Don't miss it out!

It includes...

- Merge symbols from linked libraries ⭐️⭐️⭐️
- Whole brand new UI
- Merge all symbols from a single window
- List and Card view
- Updates back in native Sketch
- And many many more...

Hope you like it! And happy merging!
