### ISSUE TITLE
Merge ONLY local symbols

### ISSUE THREAD

**Issue by frankparadiso** [oodesign/merge-duplicate-symbols#68]
Hey there,
I'm using Merge Duplicate Symbol (I purchased the license) and I'm writing because I can't merge only local symbols.
I mean... I have a Sketch file with a symbol page (that contains local symbols) and, in the same file, I use symbols from a linked library. If I run "Symbol > Merge Symbol with the same name" it affects ALL the symbols, both local ones and shared ones. And that's weird and undesired.
How can I choose what to merge (o where to merge)?
I only want to merge the symbols that are in this file and not the ones that are linked. Can I? Is there a workaround?

Thank you

**Comment by oodesign** [comment]
Hi @frankparadiso,

Merge duplicate symbols is supposed to work within the scope of a Sketch document (just local symbols). It shouldn't be affecting external ones, but we'll check if there's a bug on our side and let you know what we find out.

Meanwhile, as a workaround, you can manually select duplicates and run 'Merge selected symbols'.

Merging symbols including external libraries is next big thing in our backlog, and this update may help solving all this issues. As soon as we release it I'll be happy to let you know :)

Thanks for your help!
