### ISSUE TITLE
Merge layer styles crashing

### ISSUE THREAD

**Issue by stefdonovan** [oodesign/merge-duplicate-symbols#69]
Every time I go to merge layer styles (I have the paid plugin) - the plugin crashes. It doesn't matter which file I use. 

Is there a way to get this fixed? My favourite plugin hasn't worked for weeks. :(

**Comment by oodesign** [comment]
Hi @stefdonovan ,

Sorry to hear that. I'm afraid we're not able to reproduce the issue you describe with our testing set, though.

Which Sketch version and plugin version are you using? Are you running Sketch on MacOS Catalina?

May you send us a Sketch file with just the symbols that are causing the issue?
You may replace its real content by dummy rectangles, if you wish to. We only need the layer styles and its names.

Thanks!

**Comment by stefdonovan** [comment]
Plugin crash.mov
<https://drive.google.com/file/d/1k7parpQ6AtwrxH_oDxS4vXhhFDoB0Np_/view?usp=drive_web>
Hi Oscar,

Thank you for your reply!

I'm using Sketch 60 and the plugin version is 5.1.0 it was purchased in the
spring by my boss. Our company for security reasons won't allow up to
update to Mojave or Catalina so I'm currently operating on High Sierra.

Unfortunately, I can't send you the original file because it is a branded
library, but it seems to occur in all files so I have attached one you can
play around with. I have also attached a screencap of this happening.

I have turned off all external libraries which I thought may have been the
issue as the plugin seems to pick up 'external' layers. It doesn't seem to
help.

Thanks again for your assistance I appreciate it!

Stephanie

**Comment by oodesign** [comment]
Hi @stefdonovan ,

In Merge Duplicates v5.1.0 we added the ability to merge similar styles, and the option of including or not external libraries styles (apart of some performance improvements and some bug fixes). Your video capture (thanks for that!) shows what looks like v5.0.2.

May you try to install v5.1.0 and let us know how it worked for you? You should be able to download it from the purchase confirmation mail Gumroad sent you (let me know if you're not able to get to it, and I'll resend it to you).

At the end of the e-mail you may find a "Merge duplicates" thumbnail link. By clicking on it you'll be directed to a Gumroad page in which you should be able to type the e-mail address that was user to complete the purchase, and download "Merge duplicates".
By doing so you'll always be able to download the plugin latest version (currently v5.1.0).

We're working actively to make the update process smoother. Meanwhile, I apologise for any inconvenience this may cause you.

Please, let me know how it worked for you.

Thanks!
