### ISSUE TITLE
Move symbol function

### ISSUE THREAD

**Issue by aparajita** [oodesign/merge-duplicate-symbols#7]
Thanks for a great plugin! Since you already have the code in place to replace one master symbol with another, how hard would it be to add a function to move selected symbol masters to another page?

**Comment by oodesign** [comment]
Hi! I'm not really sure if I got the idea :'D
Currently it keeps the selected symbol's master in whatever page it is. Do you mean that, when merging symbols, you need to move the selected symbol's master to a specific page you may choose?

**Comment by aparajita** [comment]
An example:

- I create a symbol on page 1.
- Later on I decide I want to move it to page 2.

I can copy it to page 2 and then use your plugin to merge the two into the page 2 version. But it would be a lot easier if I just **moved** the original from page 1 to page 2.

**Comment by oodesign** [comment]
But... you can just drag the symbol from Page1 to Page2 (in the Sketch pages list), and that's it, isn't it?

**Comment by aparajita** [comment]
I had absolutely no idea you could do that! Thank you!
