### ISSUE TITLE
Please do not include all Libraries by default

### ISSUE THREAD

**Issue by jarobauer** [oodesign/merge-duplicate-symbols#75]
Hi, please do not include all Libraries by default since it can lead to really long loading times. Should be a choice.

**Comment by oodesign** [comment]
Hi @jarobauer ,

Thanks a lot for your feedback!

We're actively working on making this preferences persistent, so that Merge Duplicates "remembers" your previous choices. Would that help solve the issue?

**Comment by jarobauer** [comment]
Hi @oodesign , if my previous preference would be remembered it would surely help!

**Comment by oodesign** [comment]
Hi @jarobauer ,

We just released v6.3.0, that includes a "Settings" environment in which you may define if you wish Merge Duplicates to include libraries by default (on all commands) or not.

May you please give it a try and let us know how it works for you?

Thanks! 🥰
