### ISSUE TITLE
Merging resets overrides and size

### ISSUE THREAD

**Issue by RaphyRaph** [oodesign/merge-duplicate-symbols#8]
When merging a symbol, it should try to keep the label overrides. In Sketch, if you change a symbol by switching it in the symbol dropdown, any override will be kept. The plugin should replicate that behavior.

**Comment by oodesign** [comment]
Wow, didn't notice that one! :O
We'll take a look at it and as soon as we do have some details we will be sure to let you know here.
Thanks for the feedback!

**Comment by Maikenvv** [comment]
I love your plugin. Unfortunately I also have the same problem. It just sets the override to non and shows '///' in place of the previous symbol. Even more annoying: it also forget the overrides within that override (for example: texts).

**Comment by oodesign** [comment]
Hello!

I've just released v2.1.0, which solves the label overrides issue.
It works pretty much like the "Replace With" built-in feature. It keeps the label overrides, but I'm afraid it can't keep the symbol overrides.

Hope it helps!
