### ISSUE TITLE
Feedback 6.0.16

### ISSUE THREAD

**Issue by richardsison** [oodesign/merge-duplicate-symbols#80]
## Bug
- **Toggling local styles only doesn't work as I expected**.
  - When I toggle "Include all enabled libraries text styles", I expect it to only show conflicts with my Local Styles. [Toggling the checkbox does change the results](https://d.pr/v/MGU09a), but I'm not exactly sure what it's showing me in either.
  - Context: I am working in a library that is referencing _another_ library (within Abstract) with text styles with **exactly the same names** but for Mobile font sizes — the reason I need to scope this feature is because I want to merge **actual duplicates** (i.e. duplicates within my current document), but I don't want to override my mobile-specific text styles that share the same name.
  - For reference, the [Automate Sketch plugin seems to locate styles exactly as I want them](https://d.pr/i/B2u7tK) but the problem here is that the function seems to be broken on Sketch 64. Your plugin merges correctly, except there are some styles that I'm unable to merge correctly ([like this one](https://d.pr/i/CyA8MG)) — because it's treating the same name (regardless of location) as a duplicate, I can't fix my "true duplicates" unless I unlink the mobile typography library.

## Enhancements
- **Order of text styles alphabetically (or grouped like Components Sidebar)**
  - They should at least be alphabetically ordered (so it's the same as the Components Sidebar view). 
  - Ideally if they had some sort of grouping (again like the Components Sidebar), that would be better so the list would be more scannable and less long.
- **Sidebar can't be resized.** Not being able to resize the sidebar means I can't easily see what the text style's name is unless I click on the item in the sidebar. This could get fixed with an approach like above, but otherwise I'd just need to be able to resize the sidebar (and maybe to have the text style names wrap onto multiple lines…)

**Comment by oodesign** [comment]
Hi @richardsison ,

This is awesome! Thanks a lot for taking so much time and effort to arrange all this issues and feedback together!

### About merging styles

Before going at it --> I think I get your point, and we may need to redesign a bit the plugin to make sure it can be used also in this scenarios you describe. I'll be happy to let you know when this gets into Merge Duplicates, but meanwhile, let me describe what it currently does.

We handle three different scenarios, regarding styles:

- ❶ Styles that are defined locally in your file (whether they're used or not)
- ❷ External styles (from a linked library) **that are in use** in your file
- ❸ External styles that exist in linked libraries, but **that are not in use** in your file

When you use "Merge styles with the same name":

**With "Include all enabled libraries" OFF**:

- Merge Duplicates will find all styles **that are in use** in your document (note that this include ❶ and ❷), and try to find local styles that match (same name) with them.
- The purpose below that is to be able to find styles that are defined locally that may be redundant with the library ones.
- Said differently, be able to find layers using a local style when they should be using the library one.

**With "Include all enabled libraries" ON**:

- Pretty much the same, but considering ❶, ❷, and ❸ in the comparison
- The purpose below that is to be able to fins redundant styles considering all of your styles (whether they come from the local file or linked libraries).
- The styles from linked libraries will not be deleted (as we don't have access to those, and even if we did it could be dangerous). Merge Duplicates will just apply the style you decide to keep, remove the discarded local styles, and remove all references to the discarded external styles in your local Sketch file.

### About that style you can't merge

Merge styles with the same name will only allow you to choose one of them, as it's the most common merging scenario, and we want that feature to be as straightforward and simple as possible.

I'd suggest to use the **Merge Styles (from list)** command instead, that displays all styles in your file (and linked libraries if you enable the "Include enabled libraries styles"), and allows you to manually select which styles you'd like to merge.

You may need to select the two styles you want to merge, choose the one you want to keep in the right panel, and hit Merge.

### About the enhancements

**Sort alphabetically (or grouped like Components)**

Absolutely. Makes total sense and it should have been there from minute 0 😅. 
Grouping may be a tricky one, but I'm sure we may be able to add the alphabetical order soon. Stay tuned for updates!

**Be able to resize sidebar**

Sure! We're working on this one. I'll let you know when it makes it to Merge Duplicates.


<br/><br/>
Just hope this helps a bit, but please let me know if you have any question, or some of those points may need further detail or discussion.

Again, thanks a lot for reaching out, for the awesome feedback and for helping us make it better. 

Thanks a lot! 🥰

**Comment by richardsison** [comment]
Thanks a lot for responding! That makes a lot of sense.

Your suggestion would indeed work though I'll probably just wait until the alphabetical sorting and resizable sidebar are at least implemented first — it's really difficult to find the styles I want to merge at the moment. 

The thing with this approach is that, it means that I'll need to see a duplication first and then manually fix it. I would much prefer being able to just do a blanket merge but from the sounds of it, based off how the plugin operates it'd require a lot of work.

In any case, keep up the good work and thanks for responding!

**Comment by oodesign** [comment]
Yup, I totally understand...

We're actively working on some improvements (and thinking about some others) that may make all of this a bit better.

I'll make sure to let you know when they make it to the plugin so that you can take a look and let us know how they worked for you.

Thanks a lot your feedback!

**Comment by oodesign** [comment]
Hi @richardsison ,

We just released v6.0.17, which now displays symbols sorted alphabetically.
May you give it a try and let us know how it worked for you?

Thanks!

**Comment by richardsison** [comment]
Awesome! I tried it on the Layer Styles list and it works perfectly. I just wish i could resize the sidebar (which I know is being worked on). Without resizing I can't see a pretty important part of the style name.

**Comment by oodesign** [comment]
Hi @richardsison ,

Happy it works well for you!
And sure, I'm keeping this issue as open until the resizing sidebar is in :)

**Comment by oodesign** [comment]
Hi @richardsison ,

We just released v8.5.1, that does allow to resize the left side panel.
Could you check it out and let us know how it worked for you?

Thanks!
