### ISSUE TITLE
[Improvement] Also pick up symbols with 'copy #' in name

### ISSUE THREAD

**Issue by Maikenvv** [oodesign/merge-duplicate-symbols#9]
Hi, as I said in the other issue, I really love the plugin. I use it in combination with symbol organizer, which can label duplicates as 'copy #'. Is it possible for symbol merger to also include those in the search?

**Comment by oodesign** [comment]
Hi!

After some discussion we decided not to include variants of the symbol name in the Merge Duplicate Symbols plugin.

Maybe the "Merge the selected symbols" feature (which is already in our backlog, but not prioritized & scheduled yet) could be useful for you. It will allow users to choose manually several symbols (even if they don't have the same name), and ask them to decide which one should be kept (and run the rest of the plugin as it does now).

Meanwhile, you could use the "Rename it" plugin, which allows you to select several layers and rename them really easily.
