### ISSUE TITLE
Merging text style with library text style

### ISSUE THREAD

**Issue by Myeche** [oodesign/merge-duplicate-symbols#92]
Hi 
I am trying to merge some file text styles with my library text file but it doesn't work. It also doesn't work within the same text file if I don't uncheck the "all libraries" option.
I currently run Sketch 66.1 on Catalina OS 10.15.5
I am sending you my logs by email if you want to take a look :)
Thank you

**Comment by oodesign** [comment]
Hi @Myeche ,

Sorry to hear that! And thanks a lot for all details and logs you already sent us. That really helps a lot! 🥰

In the logs you sent us there is a first "Merge Selected Styles" operation that seems to have finished successfully, and a second one that had an issue when trying to present the window to select the style. Was, indeed, the first operation successful?

Regarding the issue, may you give us more detail (or screenshots or screen recording) about it? Does it show the window, but gets stuck there? Does it list the available styles to pick the one you want to keep? Or doesn't it even show the window?

Sometimes it may happen that the "Merge" window is already open when you trigger the Merge command again (it's still open, but it's under the Sketch window or some other), which may lead to some issues like the one we see in your log. May it be the case here(*)? 

(*) You may see all open windows by pressing F3, but please note that the MergeDuplicates window will only show up there if Sketch is the "active" app, so make sure to click on Sketch first 😅.

Thanks!

**Comment by oodesign** [comment]
Hi @Myeche ,

Are you still having this issue with Merge Duplicates?

Thanks!

**Comment by Myeche** [comment]
Hi @oodesign, I am so sorry I spaced out on that, it seems that the issue is gone for now. Thank you for you answer

**Comment by oodesign** [comment]
Glad to hear that!

I'm closing this issue as it seems to work back for you. Anyway, please feel free to reopen it (or create a new one) if you continue to have issues with the plugin.

Thanks a lot!
