### ISSUE TITLE
Not detecting symbols with same name

### ISSUE THREAD

**Issue by tiagomaricate** [oodesign/merge-duplicate-symbols#93]
I have two symbols with the same name very close to each other.
But the plugin simply won't detect.

**Comment by oodesign** [comment]
Hi @tiagomaricate ,

Sorry to hear that!

In the past we've seen a few cases where symbol name (in Sketch) contained some hidden special characters that was causing Merge Duplicates not to identify them as equal.

If it may be the case...

- Does Merge Duplicates find the duplicate if you just create a brand new symbol from scratch and manually type in the same symbol name of one of those symbols?

- Does Merge Duplicates work fine if you manually rename both symbols from scratch?

Thanks for reaching out!

**Comment by oodesign** [comment]
Hi @tiagomaricate ,

Are you still experiencing this issue with Merge Duplicates?

Thanks!
