### ISSUE TITLE
Team License issue 

### ISSUE THREAD

**Issue by billybailey** [oodesign/merge-duplicate-symbols#96]
**"Team license : a shared license for the team, no matter how big it is"**

First of all, thank you for developing a really cool plug-in.

We bought a team license yesterday. We think there is no limit to the number of devices. However, additional registration was blocked after registering for just 1 device.

Did we get it wrong? Is there a device limitation?

Should I purchase single license as many as the number of team members?

if so, I would like a refund.

Thank you.

**Comment by oodesign** [comment]
Hi @billybailey ,

Sure, the team license is for as many devices you may need.
May you please check which Merge Duplicates version are you using? Team license is supported from 6.4.0 (current one).

Thanks for reaching out!

**Comment by billybailey** [comment]
Solved!
Thank you
